### PR TITLE
fix(server-ui):issue-67 Added Proper Escaping quotes in scripts:'build' to work in powershell

### PR DESCRIPTION
**Pull request by bathini79**
Issue: Dev server not starting
Resolution: its not starting from powershell cmd (Windows) Becaause of build in "build": "run-p "build:*"" .
Server is not able properly espace single quotes , this PR solves that .
Reference: https://stackoverflow.com/questions/70306554/pnpm-run-on-multiples-projects-based-on-location
image

### CODE REVIEW

**Comment by Nishchit14** [comment]
If you'll search in the whole project `"build": "run-p 'build:*'",` you'll find other places too. would you mind to apply changes there too?

image

**Comment by bathini79** [comment]
Sure, I can . Only these two were stopping to run the server. So, I fixed for these two services . I'll be doing up for other services in case

**Comment by bathini79** [comment]
Done @Nishchit14

**Review by Nishchit14 — APPROVED** [review]

**Comment by Nishchit14** [comment]
#70 #67

**Pull request merged**
