### PR TITLE
Fix zustand console warnings

### LINKED ISSUE #77: fix zustand warnings
**Description**
[after migrating to the zustand v4](https://docs.pmnd.rs/zustand/migrations/migrating-to-v4), it shows the warning in console. Follow the migration guide to avoid it.

image

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
### Description

- [x] Warnings related to `Default export`
- [ ] Warnings related to `zustand/context` --> this requires refactor for [`./playgrounds/firecamp-graphql/src/store/store.ts
`](https://github.com/firecamp-dev/firecamp/blob/08791d3a6d7cf84875f3c8cd81554d572953767c/playgrounds/firecamp-graphql/src/store/store.ts)

### Screenshots (optional)

|Before|After|
|:---:|:---:|
|image|image|

Fixes #77

### CODE REVIEW

**Comment by Nishchit14** [comment]
I'll create a separate issue for the second point. Need to review https://github.com/pmndrs/zustand/discussions/1180 first.

**Review by Nishchit14 — APPROVED** [review]
LGTM :)

**Comment by Siddhant-K-code** [comment]
> I'll create a separate issue for the second point. Need to review https://github.com/pmndrs/zustand/discussions/1180 first.

Agreed, let's go ahead and merge this one. We can address the second issue in a subsequent PR. Once this is merged, we'll be down to just one warning, a significant improvement from the initial eight warnings :)

**Comment by Nishchit14** [comment]
The actual migration guide is written here.

https://docs.pmnd.rs/zustand/previous-versions/zustand-v3-create-context#migration

**Comment by Nishchit14** [comment]
> > I'll create a separate issue for the second point. Need to review [pmndrs/zustand#1180](https://github.com/pmndrs/zustand/discussions/1180) first.
> 
> Agreed, let's go ahead and merge this one. We can address the second issue in a subsequent PR. Once this is merged, we'll be down to just one warning, a significant improvement from the initial eight warnings :)

Agree, I'll check this in locally once and then merge, probably by the next morning.

**Review by Nishchit14 — APPROVED** [review]

**Pull request merged**
