### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fahurox**
Fixed typos and added missing commas

### CODE REVIEW

**Comment by jsoref** [comment]
fwiw, assuming you've replaced all instances, in `.github/actions/spelling/line_forbidden.patterns`, you could add something like:

```
# s.b. API(s)
\bapis?\b
```

to discourage people from using `api`/`apis`.

**Review by Nishchit14 — APPROVED** [review]

**Review by shreya-gr — APPROVED** [review]
LGTM

**Comment by Nishchit14** [comment]
> fwiw, assuming you've replaced all instances, in `.github/actions/spelling/line_forbidden.patterns`, you could add something like:
> 
> ```
> # s.b. API(s)
> \bapis?\b
> ```
> 
> to discourage people from using `api`/`apis`.

I'll add it explicitly, so I can merge this PR.

**Comment by Nishchit14** [comment]
Thank you for your contribution @fahurox 🙏

**Pull request merged**
