### PR TITLE
Firecamp Desktop App

### PR DESCRIPTION
**Pull request by Nishchit14**
#62

### CODE REVIEW

**Comment by LukeHagar** [comment]
Hey @Nishchit14,

I was going to attempt to fork the repo and help with some things like the spelling errors GitHub advanced security flagged on, but I'm getting this error trying to switch to this branch.

image


If I can help with Electron at all I would be happy to, and good luck with the Desktop release!

**Comment by Nishchit14** [comment]
@LukeHagar Thanks for forking the repo, First you can run the app in web mode with `pnpm dev` command. You can contribute whatever you wish there. If anything specific to the desktop app, you can consider `pakcages/firecamp-electron` directory to navigate. just run `pnpm start` to open the local desktop app.

**Comment by Nishchit14** [comment]
@jsoref Can you please help here why the job is failing?

**Comment by Nishchit14** [comment]
Thank you @jsoref for the PR with fixes, Those empty files were generated with Tauri initialisation process. 

Also where can I see all these error logs? I tried to debug the failed job but I couldn't find anything helpful

**Comment by jsoref** [comment]
For a given commit, you can click the ❌ on the right (a similar one at the bottom of a PR would work, but it's now a ✅ , so I can't link there):
image
And then click [`Details`](https://github.com/firecamp-dev/firecamp/actions/runs/8139280566/job/22242094103):
image
And then click [`Summary`](https://github.com/firecamp-dev/firecamp/actions/runs/8139280566) on the left:
image
Then scroll down to the [bottom](https://github.com/firecamp-dev/firecamp/actions/runs/8139280566#summary-22242094103)
image

----

The first bits are in:
#### Unrecognized words (4)

APPIMAGE
eciesjs
rustc
togglefullscreen

----

The second set of things were covered in this:

<details><summary>Some files were automatically ignored :see_no_evil:</summary>

These sample patterns would exclude them:
```
^\Qpackages/firecamp-tauri/src-tauri/rustc-ice-2023-08-29T12:21:32.539513Z-24344.txt\E$
^\Qpackages/firecamp-tauri/src-tauri/rustc-ice-2023-09-01T10:38:16.464703Z-21654.txt\E$
```

You should consider adding them to:
```
.github/actions/spelling/excludes.txt
```

File matching is via Perl regular expressions.

To check these files, more of their words need to be in the dictionary than not. You can use `patterns.txt` to exclude portions, add items to the dictionary (e.g. by adding them to `allow.txt`), or fix typos.
</details>

----

And indication about forbidden patterns is in the `Errors` section:

<details><summary>Errors (3)</summary>

See the [:open_file_folder: files](https://github.com/firecamp-dev/firecamp/pull/164/files/) view, the [:scroll:action log](https://github.com/firecamp-dev/firecamp/actions/runs/8139280566/job/22242094103#step:4:1), [:angel: SARIF report](https://github.com/firecamp-dev/firecamp/security/code-scanning?query=is:open+pr:164), or [:memo: job summary](https://github.com/firecamp-dev/firecamp/actions/runs/8139280566/attempts/1#summary-22242094103) for details.

[:x: Errors](https://github.com/check-spelling/check-spelling/wiki/Event-descriptions) | Count
-|-
[:information_source: binary-file](https://github.com/check-spelling/check-spelling/wiki/Event-descriptions#binary-file) | 2
[:x: check-file-path](https://github.com/check-spelling/check-spelling/wiki/Event-descriptions#check-file-path) | 2
[:x: forbidden-pattern](https://github.com/check-spelling/check-spelling/wiki/Event-descriptions#forbidden-pattern) | 2

See [:x: Event descriptions](https://github.com/check-spelling/check-spelling/wiki/Event-descriptions) for more information.

</details>

----

The specific details of everything are in:

<details><summary>Details :mag_right:</summary>

...

</details>

**Comment by Nishchit14** [comment]
Thank you @jsoref for your all help 🙌

**Pull request merged**
